[env:esp32c3_oled]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<main_oled.cpp>

; 串口波特率配置
monitor_speed = 115200
upload_speed = 921600

; 确保串口使用 USB CDC 输出
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; 修改分区表，提供 Huge APP (3MB No OTA / 1MB SPIFFS) 支持全字库
board_build.partitions = huge_app.csv

; 依赖库配置
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    olikraus/U8g2 @ ^2.34.22

[env:esp32c3_tft]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<main_tft.cpp>

; 串口波特率配置
monitor_speed = 115200
upload_speed = 921600

; 确保串口使用 USB CDC 输出
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; 修改分区表
board_build.partitions = huge_app.csv

; 依赖库配置
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit GFX Library @ ^1.12.1
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
    olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
